services:
  public:
    entreprise:
      url: ${SERVICE_PUBLIC_ENTREPRISE}

feature:
  batch:
    chunk-size: ${COMPANIES_BATCH_CHUNK_SIZE}
    output-folder: ${COMPANIES_BATCH_OUT_FOLDER}
    entreprise:
      siret-companies-file-path: ${SIRET_COMPANIES_FILE_IN}
    
feign:
  autoconfiguration:
    jackson:
      enabled: true

spring:
  main:
    web-application-type: none
