version: "3.5"
services:
  # APP *****************************************
  worker-compant:
    image: intelciaitsolution.azurecr.io/worker-company:latest
    restart: unless-stopped
    build: ./
    ports:
      - 8090:8090
